# src/main/resources/application.yaml
spring:
  datasource:
    url: ${DATABASE_URL}
    driver-class-name: org.postgresql.Driver # Ezt is add meg expliciten, ha még nincs!
  jpa:
    hibernate:
      ddl-auto: update # Vagy none/validate, attól függ, mit szeretnél
    show-sql: true # Hibakereséshez hasznos
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect # Ezt is add meg expliciten!

server:
  port: ${SERVER_PORT:8080} # Vagy ${PORT:8080}, ha Render alapértelmezett PORT-ját szeretnéd használni
  # De mivel te beállítottál SERVER_PORT=10000-et, ez a helyes.