spring:
  datasource:
    url: ${DATABASE_URL} # Ezt a Railway-ről kapott MySQL DATABASE_URL-ből fogja venni
    driver-class-name: com.mysql.cj.jdbc.Driver # Fontos, hogy ez legyen
  jpa:
    hibernate:
      ddl-auto: validate # Vagy amit használsz (pl. update fejlesztéshez)
    show-sql: false
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL8Dialect # Ha MySQL 8+, vagy MySQL5Dialect ha régebbi

server:
  port: ${PORT:8080} # A Railway általában PORT változót használ