server:
  port: 5432

spring:
  datasource:
    url: postgresql://backend_db_gq0c_user:XAmRBrNzLFsm0oCsZPKyrEogKO8ZdY0P@dpg-d0offifdiees739b5uv0-a.frankfurt-postgres.render.com/backend_db_gq0c
    username: backend_db_gq0c_user
    password: XAmRBrNzLFsm0oCsZPKyrEogKO8ZdY0P
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true
